const battleEngravings = [
    'Adrenaline',
    'All-Out-Attack',
    'Ambush Master',
    'Awakening',
    'Barricade',
    'Broken Bone',
    'Contender',
    'Crisis Evasion',
    'Crushing Fist',
    'Cursed Doll',
    'Disrespect',
    'Divine Protection',
    'Drops of Ether',
    'Emergency Rescue',
    'Enhanced Shield',
    'Ether Predator',
    'Expert',
    'Explosive Expert',
    'Fortitude',
    'Grudge',
    'Heavy Armor',
    'Hit Master',
    'Increases Mass',
    'Keen Blunt Weapon',
    'Lightning Fury',
    'MP Efficiency Increase',
    'Magick Stream',
    'Master Brawler',
    'Master of Escape',
    'Master\'s Tenacity',
    'Max MP Increase',
    'Necromancy',
    'Precise Dagger',
    'Preemptive Strike',
    'Propulsion',
    'Raid Captain',
    'Shield Piercing',
    'Sight Focus',
    'Spirit Absorption',
    'Stabilized Status',
    'Strong Will',
    'Super Charge',
    'Vital Point Hit'
];

export default battleEngravings;